s=input('enter the integer:')
i=input('enter the img value:')
c=str(s)
d=chr(s)
print "Interger :",int(c)
print "Float : ",float(c)
print "Complex :",complex(s,i)
print "String :",str(s)
print "Expression :",repr(s)
print "evaluation :",eval(c)
print "Tuple:",tuple(c)
print "List:",list(c)
print "set:",set(c)
print "frozenset:",frozenset(c)
print "character:",chr(s) 
print "unicode:",unichr(s)
print "hex:",hex(s)
print "oct:",oct(s)
print "interger :", ord(d)
